<template>
  <section class="settings-panel">
    <header><div><p>SYSTEM SETTINGS</p><h1>系统配置</h1><span>模型密钥仅由服务器环境变量管理，页面只显示配置状态。</span></div><div class="settings-actions"><button type="button" :disabled="loading || saving" @click="load">刷新</button><button class="save-button" type="submit" form="system-settings-form" :disabled="!form || loading || saving">{{ saving ? '正在保存…' : '保存配置' }}</button></div></header>
    <form v-if="form" id="system-settings-form" @submit.prevent="save">
      <section><h3>平台运行</h3><div class="grid"><label>允许注册<input v-model="form.register_enabled" type="checkbox" /></label><label>默认生成配额<input v-model.number="form.default_user_quota" type="number" min="0" /></label><label>构建模式<select v-model="form.build_mode"><option value="mock">Mock</option><option value="real">Real</option></select></label><label>命令模式<select v-model="form.command_mode"><option value="shell">Shell（本地开发）</option><option value="sandbox">Sandbox</option><option value="docker">Docker</option></select></label><label>生成并发<input v-model.number="form.generation_concurrency" type="number" min="1" max="16" /></label><label>修改并发<input v-model.number="form.modification_concurrency" type="number" min="1" max="32" /></label><label>任务超时（秒）<input v-model.number="form.task_timeout_seconds" type="number" min="30" max="7200" /></label><label>需求最大字符数<input v-model.number="form.max_requirement_length" type="number" min="100" max="50000" /></label><label>最大模型决策轮次<input v-model.number="form.agent_max_model_steps" type="number" min="1" max="500" /></label><label>最大实际工具调用数<input v-model.number="form.agent_max_tool_calls" type="number" min="1" max="2000" /></label><label>软预算预警比例<input v-model.number="form.agent_soft_limit_ratio" type="number" min="0.5" max="0.95" step="0.05" /></label><label>最大无进展次数<input v-model.number="form.agent_max_no_progress_steps" type="number" min="2" max="200" /></label></div></section>
      <section><h3>代码生成模型 <b :class="form.llm_api_key_configured?'ok':'warn'">{{ form.llm_api_key_configured?'密钥已在服务器配置':'未配置密钥' }}</b></h3><div class="grid"><label>模型名称<input v-model.trim="form.llm_model" /></label><label>兼容 API 地址<input v-model.trim="form.llm_base_url" type="url" placeholder="https://api.example.com" /></label><label>推理强度<select v-model="form.llm_reasoning_effort"><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></label><label>启用思考<input v-model="form.llm_thinking_enabled" type="checkbox" /></label></div></section>
      <section><h3>视觉评估模型 <b :class="form.eval_vision_api_key_configured?'ok':'warn'">{{ form.eval_vision_api_key_configured?'密钥已在服务器配置':'未配置密钥' }}</b></h3><div class="grid"><label>Provider<select v-model="form.eval_vision_provider"><option value="disabled">disabled</option><option value="qwen_compatible">qwen_compatible</option></select></label><label>模型名称<input v-model.trim="form.eval_vision_model" /></label><label>兼容 API 地址<input v-model.trim="form.eval_vision_base_url" type="url" placeholder="https://api.example.com" /></label><label>启用思考<input v-model="form.eval_vision_thinking_enabled" type="checkbox" /></label></div></section>
      <footer><small>模型端点和行为参数保存后立即用于后续任务；并发调整在服务重启后生效。</small></footer>
    </form><p v-else-if="loading">正在加载配置…</p>
  </section>
</template>
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import { getAdminSettings, updateAdminSettings, type AdminSettings } from "../api/admin";
const form = ref<AdminSettings>(); const loading = ref(false); const saving = ref(false);
async function load() { loading.value=true; try { form.value=await getAdminSettings(); } catch { ElMessage.error("无法读取系统配置"); } finally { loading.value=false; } }
async function save() { if (!form.value) return; saving.value=true; try { form.value=await updateAdminSettings(form.value); ElMessage.success("系统配置已保存"); } catch (error:any) { ElMessage.error(error.response?.data?.detail || "保存失败，请检查配置值"); } finally { saving.value=false; } }
onMounted(load);
</script>
<style scoped>
.settings-panel{margin-top:20px;border:1px solid #dbe3f0;border-radius:8px;padding:24px;background:#fff}.settings-panel header,.settings-panel footer{display:flex;align-items:center;justify-content:space-between;gap:16px}.settings-panel header p{margin:0;color:#3164ca;font:700 11px monospace;letter-spacing:.1em}.settings-panel h2{margin:6px 0;font-size:24px}.settings-panel h3{margin:0 0 14px;font-size:16px}.settings-panel header span,.settings-panel small{color:#71809a;font-size:13px}.settings-panel section{margin-top:22px;padding-top:20px;border-top:1px solid #e8edf5}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 18px}.grid label{display:grid;gap:7px;color:#51617d;font-size:13px;font-weight:700}.grid input:not([type=checkbox]),.grid select{box-sizing:border-box;width:100%;min-height:36px;border:1px solid #cbd6e8;border-radius:5px;padding:7px;background:#fff;color:#263855}.grid input[type=checkbox]{justify-self:start;width:17px;height:17px}.settings-panel footer{margin-top:24px}.settings-panel button{border:1px solid #2861dc;border-radius:6px;padding:8px 13px;background:#2861dc;color:#fff;font-weight:700;cursor:pointer}.settings-panel header button{background:#fff;color:#2858b8;border-color:#c9d6ec}.settings-panel button:disabled{opacity:.6;cursor:wait}.settings-panel b{margin-left:7px;border-radius:4px;padding:3px 6px;font:11px monospace}.ok{background:#e4f6ec;color:#178051}.warn{background:#fff4d8;color:#9b6a00}@media(max-width:800px){.grid{grid-template-columns:1fr}.settings-panel header,.settings-panel footer{align-items:flex-start;flex-direction:column}}
.settings-panel { margin-top:0; border:0; border-radius:0; padding:0; background:transparent; }
.settings-panel header { align-items:flex-end; padding:18px 0 22px; border-bottom:1px solid #d9e1ee; }
.settings-panel h1 { margin:7px 0; font-size:34px; }
.settings-actions { display:flex; flex-shrink:0; gap:8px; }
.settings-panel header .save-button { background:#2861dc; border-color:#2861dc; color:#fff; }
.settings-panel form { margin-top:20px; padding:20px 24px; border:1px solid #dbe3f0; border-radius:8px; background:#fff; }
.settings-panel form > section:first-child { margin-top:0; padding-top:0; border-top:0; }
@media(max-width:800px) { .settings-panel header { align-items:flex-start; } .settings-panel form { padding:18px; } }
</style>
