"""add cancel_requested to generations

Revision ID: 1c4243ee8fbd
Revises: e0806b14bcc1
Create Date: 2026-08-14 21:37:10.216004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c4243ee8fbd'
down_revision: Union[str, None] = 'e0806b14bcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('cancel_requested', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'cancel_requested')
    # ### end Alembic commands ###
