<template>
  <main class="admin">
    <header class="topbar"><button class="brand" @click="$router.push('/')">AI 灵码平台 <small>运营控制中心</small></button><nav><button v-for="item in sections" :key="item.key" :class="{ on: section === item.key }" @click="section = item.key">{{ item.label }}</button></nav><button class="back" @click="$router.push('/')">项目工作区</button></header>
    <section class="title"><div><p>PLATFORM CONTROL</p><h1>{{ currentSection?.label }}</h1><span>{{ currentSection?.hint }}</span></div><button @click="load">刷新数据</button></section>
    <div v-if="loading" class="loading">正在读取管理数据…</div>
    <template v-else-if="data">
      <section v-if="section === 'dashboard'" class="dashboard"><div class="metrics"><article v-for="metric in metrics" :key="metric.label"><small>{{ metric.label }}</small><strong>{{ metric.value }}</strong><span>{{ metric.note }}</span></article></div><section class="card"><h2>当前告警</h2><p v-if="!obs?.alerts?.length" class="empty">当前没有需要处理的告警。</p><article v-for="item in (obs?.alerts || []).slice(0, 12)" :key="item.event_id" class="row"><b :class="item.level">{{ item.level }}</b><strong>{{ item.title }} · {{ item.project_name }}</strong><span>{{ item.detail }}</span></article></section></section>
      <section v-else-if="section === 'projects'" class="card"><h2>项目管理</h2><table><thead><tr><th>项目</th><th>创建者</th><th>技术栈</th><th>状态</th><th>更新时间</th></tr></thead><tbody><tr v-for="project in data.projects" :key="project.id"><td>{{ project.name }}</td><td>{{ project.owner }}</td><td>{{ project.tech_stack }}</td><td>{{ project.status }}</td><td>{{ time(project.updated_at) }}</td></tr></tbody></table><div class="operation-grid"><section><h3>任务与素材</h3><p v-for="task in data.tasks" :key="task.id" class="operation-row"><b>{{ task.kind }}</b><span>{{ task.project_name }} · {{ task.summary }}</span><em>{{ task.status }}</em><button v-if="canRetry(task)" @click="retry(task)">重新执行</button></p></section><section><h3>发布记录</h3><p v-for="deployment in data.deployments" :key="deployment.id" class="operation-row"><b>发布</b><span>{{ deployment.project_name }} · 版本 #{{ deployment.version }}</span><em>{{ deployment.is_active ? '线上' : deployment.status }}</em><a v-if="deployment.url" :href="deployment.url" target="_blank">打开</a></p></section><section><h3>项目运行观测</h3><p v-for="event in (obs?.timeline || []).slice(0, 20)" :key="event.id" class="operation-row"><b>{{ event.stage }}</b><span>{{ event.project_name }} · {{ event.summary }}</span><em>{{ event.status }}</em></p></section></div></section>
      <section v-else-if="section === 'users'" class="card"><h2>用户管理</h2><table><thead><tr><th>用户</th><th>邮箱</th><th>配额</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="user in data.users" :key="user.id"><td>{{ user.username }}</td><td>{{ user.email || '—' }}</td><td><input v-model.number="user.quota" type="number" min="0" @change="saveQuota(user)" /></td><td>{{ user.status }}</td><td><button :disabled="user.id === auth.user?.id" @click="toggleUser(user)">{{ user.status === 'active' ? '停用' : '启用' }}</button></td></tr></tbody></table></section>
      <section v-else-if="section === 'audits'" class="card"><h2>操作管理</h2><table><thead><tr><th>时间</th><th>操作者</th><th>操作</th><th>对象</th><th>详情</th></tr></thead><tbody><tr v-for="item in data.audits" :key="item.id"><td>{{ time(item.created_at) }}</td><td>用户 #{{ item.actor_id || '系统' }}</td><td>{{ item.action }}</td><td>{{ item.target_type }} #{{ item.target_id }}</td><td>{{ detail(item.detail) }}</td></tr></tbody></table></section>
      <SystemSettingsPanel v-else />
    </template>
  </main>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { getAdminObservability, getAdminOverview, retryAdminAssetJob, updateAdminUser } from "../api/admin";
import SystemSettingsPanel from "../components/SystemSettingsPanel.vue";
import { useAuthStore } from "../stores/auth";
const auth = useAuthStore(); const data = ref<any>(); const obs = ref<any>(); const loading = ref(false); const section = ref("dashboard");
const sections = [{ key: "dashboard", label: "运营大屏", hint: "全局健康与运行告警" }, { key: "projects", label: "项目管理", hint: "项目与交付状态" }, { key: "users", label: "用户管理", hint: "账户配额与启停" }, { key: "audits", label: "操作管理", hint: "可追溯的管理员操作" }, { key: "settings", label: "系统配置", hint: "平台运行参数与 AI 模型配置" }];
const currentSection = computed(() => sections.find((item) => item.key === section.value));
const metrics = computed(() => data.value ? [{ label: "项目", value: data.value.metrics.projects, note: "全部工作区" }, { label: "用户", value: data.value.metrics.users, note: "账户" }, { label: "运行任务", value: data.value.metrics.running_tasks, note: "生成、修改与素材" }, { label: "线上站点", value: data.value.metrics.online_sites, note: "当前发布" }] : []);
function time(value: string) { return new Date(value).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
function detail(value: any) { return value ? Object.entries(value).map(([key, item]) => `${key}: ${item}`).join("；") : "—"; }
async function load() { loading.value = true; try { [data.value, obs.value] = await Promise.all([getAdminOverview(), getAdminObservability()]); } catch { ElMessage.error("无法读取管理数据"); } finally { loading.value = false; } }
async function saveQuota(user: any) { try { await updateAdminUser(user.id, { quota: Number(user.quota) }); ElMessage.success("配额已更新"); } catch { ElMessage.error("更新失败"); } }
async function toggleUser(user: any) { try { await ElMessageBox.confirm(`确定${user.status === "active" ? "停用" : "启用"}用户 ${user.username} 吗？`); await updateAdminUser(user.id, { status: user.status === "active" ? "disabled" : "active" }); await load(); } catch {} }
function canRetry(task: any) { return String(task.id).startsWith("asset-") && !["pending", "running", "succeeded"].includes(task.status); }
async function retry(task: any) { try { await retryAdminAssetJob(Number(String(task.id).replace("asset-", ""))); ElMessage.success("已重新排队"); await load(); } catch { ElMessage.error("重试失败"); } }
onMounted(load);
</script>
<style scoped>
.admin{min-height:100vh;padding:88px 32px 36px;background:#f4f6fa;color:#243552}.topbar{position:fixed;z-index:3;inset:0 0 auto;height:68px;display:flex;align-items:center;gap:26px;padding:0 32px;background:#121e34;color:#fff}.brand{border:0;background:transparent;color:#fff;text-align:left;font-weight:800;cursor:pointer}.brand small{display:block;color:#92a5c7;font-size:11px}nav{display:flex;align-self:stretch}nav button{border:0;border-bottom:3px solid transparent;padding:0 13px;background:transparent;color:#aab8cf;font-weight:700;cursor:pointer}nav button.on{border-color:#4e80ff;color:#fff}.back,.title button,.card button{border:1px solid #c9d6ec;border-radius:6px;padding:7px 10px;background:#fff;color:#2858b8;font-weight:700;cursor:pointer}.back{margin-left:auto;background:#2861dc;color:#fff;border-color:#2861dc}.title{display:flex;align-items:end;justify-content:space-between;padding:18px 0 22px;border-bottom:1px solid #d9e1ee}.title p{margin:0;color:#3164ca;font:700 11px monospace;letter-spacing:.1em}.title h1{margin:7px 0;font-size:34px}.title span,.empty{color:#72809a}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:20px 0}.metrics article,.card{border:1px solid #dbe3f0;border-radius:8px;background:#fff}.metrics article{padding:18px}.metrics small,.metrics span{display:block;color:#78869e;font-size:12px}.metrics strong{display:block;margin:8px 0;font-size:30px}.card{padding:20px;overflow:auto}.card h2{margin:0 0 14px;font-size:18px}.row{display:grid;grid-template-columns:80px 220px 1fr;gap:12px;padding:11px 0;border-top:1px solid #edf0f5;font-size:13px}.row span{color:#71809a}b{border-radius:4px;padding:3px 6px;background:#e9f1ff;color:#3260ba;font:11px monospace}.critical{background:#feecef;color:#bc4057}.warning{background:#fff4d8;color:#9b6a00}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:12px;border-bottom:1px solid #edf0f5;font-size:13px}th{color:#71809a;font-size:11px}input{width:76px;padding:6px;border:1px solid #ccd6e7;border-radius:4px}@media(max-width:800px){.admin{padding-inline:14px}.topbar{padding:0 14px;gap:5px}.brand{display:none}nav{overflow:auto}.metrics{grid-template-columns:repeat(2,1fr)}.row{grid-template-columns:1fr}.title{align-items:flex-start;flex-direction:column}.back{margin-left:auto}}
.operation-grid{display:grid;gap:16px;margin-top:22px}.operation-grid section{border-top:1px solid #e5ebf4;padding-top:15px}.operation-grid h3{margin:0 0 8px;font-size:15px}.operation-row{display:grid;grid-template-columns:80px 1fr 90px auto;gap:10px;align-items:center;margin:0;padding:9px 0;border-top:1px solid #edf0f5;font-size:12px}.operation-row em{color:#71809a;font-style:normal}.operation-row a{color:#2858b8;font-weight:700}</style>
